# Generated by Django 6.0.6 on 2026-06-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('color', models.CharField(choices=[('black', 'BLACK'), ('white', 'WHITE'), ('blue', 'BLUE'), ('green', 'GREEN'), ('red', 'RED'), ('purple', 'PURPLE'), ('orange', 'ORANGE'), ('yellow', 'YELLOW'), ('pink', 'PINK'), ('brown', 'BROWN'), ('gray', 'GRAY'), ('grey', 'GREY')], max_length=100)),
                ('created_add', models.DateTimeField(auto_now_add=True)),
                ('updated_add', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-created_add'],
            },
        ),
    ]
